### ISSUE TITLE
InputFromScreen does not account for the default screen's position

### ISSUE THREAD

**Issue by Jezorko** [julianghionoiu/dev-screen-record#3]
Only the size of the screen is used to determine screen bounds ([see here](https://github.com/julianghionoiu/dev-screen-record/blob/8d5761d1aaefdc3513e263dcbe3689b8a3b4949b/src/main/java/tdl/record/screen/image/input/InputFromScreen.java#L25)).

Consider the following use case:

![two screens of various sizes, primary screen positioned on the right from the secondary screen](https://i.imgur.com/c56c829.png)

There are two screens, **primary** and **secondary**.
The primary screen's dimensions are 1600px by 900px. It is positioned to the right from the secondary screen, with position offset being equal to the size of the secondary screen—in this case 1400px.

The `InputFromScreen` class will determine primary screen bounds correctly as 1600x900, but without the position. Therefore the region marked with a red border on the image below will be recorded:

![two screens like on the image above, with a red border indicating the recording region](https://i.imgur.com/PplvXcd.png)

This can be fixed by using the [GraphicsConfiguration#getBounds()](https://docs.oracle.com/javase/8/docs/api/java/awt/GraphicsConfiguration.html) method of the default [GraphicsDevice](https://docs.oracle.com/javase/8/docs/api/java/awt/GraphicsDevice.html) like:

```java
this.screenBounds = GraphicsEnvironment.getLocalGraphicsEnvironment()
                                       .getDefaultScreenDevice()
                                       .getDefaultConfiguration()
                                       .getBounds();
```

Now, I did not check if the rectangle is properly handled downstream, so this might not be a sufficient solution all by itself.

**Comment by julianghionoiu** [comment]
Thanks a lot for this!
That is indeed a nicer way of determining the screen size.

**Comment by Jezorko** [comment]
> Yes looks like the only test covering this is the manual acceptance test. I am ok with this for now.
Do you have any suggestions on how this can be tested?

@julianghionoiu yup:
Set up your screens like on the picture (primary to the right from secondary).
On Linux you can use `arandr`, my configuration generated by it:
```bash
xrandr --output HDMI1 --mode 1440x900 --pos 0x0 --rotate normal \
       --output eDP1 --primary --mode 1600x900 --pos 1440x0 --rotate normal
```
Then try recording the screen. If only the entire primary screen is shown on the recording, it means it works (:

**Comment by julianghionoiu** [comment]
Nice one! Thanks for the command. 

Do you know if there is a way to fake an screen input. Ideally I would like to generate a well known input and then assert that the video contains that exact input.

Cheers,
 Julian

**Comment by Jezorko** [comment]
@julianghionoiu I know what you have in mind. It is possible with [Xvfb](https://www.x.org/archive/X11R7.6/doc/man/man1/Xvfb.1.xhtml), albeit a bit tricky.

You could create two virtual frame devices like:

```bash
Xvfb :1 -screen 0 20x20x16 -fbdir /tmp # creates /tmp/Xvfb_screen0
Xvfb :1 -screen 1 10x10x16 -fbdir /tmp # creates /tmp/Xvfb_screen1
```

Then I'd suggest displaying on each of them a full-screen window with varying colors.
And then possibly run the application on them (no idea how though).

Afterwards, you could check if the recording consists of only a single-color frame. That would mean the screens are not overlapping.

This is just an idea that might work but I haven't tested it myself.

**Comment by julianghionoiu** [comment]
Yea, I need to play around with it, but this is what I am looking for.
