### ISSUE TITLE
Recording does not work if screen height is odd

### ISSUE THREAD

**Issue by julianghionoiu** [julianghionoiu/dev-screen-record#5]
```
20:45:18.435 ERROR [VideoRec]      - [libx264 @ 00000000003DB9A0] height not divisible by 2 (1920x975)
20:45:18.492 ERROR [VideoRec]      - FfmpegException::make(finalStr): could not open codec: Error number -1 occurred (-1) (VideoExceptions.cpp:118)
20:45:18.588 ERROR [VideoRec]      - Video recorder encountered exception. Recording has been stopped.
java.lang.RuntimeException: could not open codec: Error number -1 occurred (-1)
	at io.humble.video.VideoJNI.Encoder_open(Native Method) ~[humble-video-noarch-0.2.1.jar:0.2.1]
	at io.humble.video.Encoder.open(Encoder.java:154) ~[humble-video-noarch-0.2.1.jar:0.2.1]
	at tdl.record.screen.video.VideoRecorder.open(VideoRecorder.java:118) ~[dev-screen-record-0.0.6.jar:na]
	at tdl.record_upload.video.VideoRecordingThread.run(VideoRecordingThread.java:35) ~[record-and-upload-0.0.16.jar:na]
```

**Comment by neomatrix369** [comment]
Any ideas how we reproduce this issue?

**Comment by neomatrix369** [comment]
I tried to reproduce the issue by switching to a screen mode with the same resolution but it didn't work, there's no easy way to make the OS accept a resolution of your choice, and then I tried to locate the place where this exception is triggered from, its this https://github.com/artclarke/humble-video/blob/6ca2c7714c18ac33ef40597f74f065a5bb0f6d15/humble-video-captive/src/main/gnu/libx264/csrc/input/avs.c#L376 line of code that triggers the error.

**Comment by neomatrix369** [comment]
I also left an issue on their github repo, see https://github.com/artclarke/humble-video/issues/128 

What are our options?
- ask users to always ensure they have even resolutions before running the program
- submit a PR with humble-video with a fix
- wait for a response from the collaborators of humble video

I suggest the workaround be an instruction in the docs, something like this is hard to reproduce and fix. And it's a highly uncommon occurrence.

I have noticed that there are a number of resolutions displays on Linux, but the one with the odd height is not allowed to selected. On Windows or the MacOS no odd height resolutions are displayed or allowed to be chosen via their respective Desktop/Monitor apps.

**Comment by julianghionoiu** [comment]
The resolutions are coupled with the size of your screen. It might be that there are screens out there with an odd height.

Another way of reproducing this is by using a virtual machine.

There something we can do about this in code, that is if the screen has an odd height, we drop the last line to make it even.

I am already preprocessing the video stream in the recorder (scaling), so that should be achievable.

**Comment by neomatrix369** [comment]
I have been playing around with various OSes including VirtualBox and have not been able to locate a resolution with an odd high, the ones with that resolution are not selectable. In my view, it's not an easy one to immediately reproduce - also what is the value of fixing it? Do you get a lot of clients with this issue? Are they running it inside the VM?

Before we can fix it, we would like to be able to reliably reproduce it - so far its not something i'm able to do.

**Comment by julianghionoiu** [comment]
Another candidate just experienced the same problem:
```
18:55:23.454 INFO  [main]          - Checking permissions
18:55:24.052 INFO  [main]          - Logging initialized @1461ms to org.eclipse.jetty.util.log.Slf4jLog
18:55:27.183 INFO  [VideoRec]      - Open the input stream
18:55:27.339 INFO  [main]          - jetty-9.4.7.v20170914
18:55:27.339 INFO  [Upload]        - Sync local files with remote
18:55:27.418 INFO  [main]          - Started ServerConnector@239b0f9d{HTTP/1.1,[http/1.1]}{localhost:41375}
18:55:27.420 INFO  [main]          - Started @4830ms
18:55:27.510 INFO  [Upload]        - Uploading file record/localstore/sourcecode_20190120T185524.srcs
18:55:27.671 INFO  [Upload]        - Finished uploading file record/localstore/sourcecode_20190120T185524.srcs
18:55:27.671 INFO  [Upload]        - Uploading file record/localstore/record-and-upload-20190120T185522.log
18:55:27.809 INFO  [Upload]        - Finished uploading file record/localstore/record-and-upload-20190120T185522.log
18:55:27.846 ERROR [VideoRec]      - [libx264 @ 0x7ff2100cf060] height not divisible by 2 (2752x1337)
18:55:27.849 ERROR [VideoRec]      - FfmpegException::make(finalStr): could not open codec: Operation not permitted (-1) (VideoExceptions.cpp:118)
18:55:27.861 ERROR [VideoRec]      - Video recorder encountered exception. Recording has been stopped.
java.lang.RuntimeException: could not open codec: Operation not permitted (-1)
	at io.humble.video.VideoJNI.Encoder_open(Native Method) ~[humble-video-noarch-0.2.1.jar:0.2.1]
	at io.humble.video.Encoder.open(Encoder.java:154) ~[humble-video-noarch-0.2.1.jar:0.2.1]
	at tdl.record.screen.video.VideoRecorder.open(VideoRecorder.java:118) ~[dev-screen-record-0.0.6.jar:na]
	at tdl.record_upload.video.VideoRecordingThread.run(VideoRecordingThread.java:35) ~[record-and-upload-0.0.16.jar:na]
18:55:28.027 INFO  [SourceRec]     - Start recording to "sourcecode_20190120T185524.srcs"
```

**Comment by julianghionoiu** [comment]
I think we might be able to add a unit test to reproduce this problem, by faking the returned screen size.

**Comment by neomatrix369** [comment]
And what are we envisioning the test to fail on? How are we constructing this test - given we have to intercept or make the program think its running on a screen with odd metrics. Dependency injection and pass it fake values? Some hints will help.

**Comment by neomatrix369** [comment]
I'm looking at it now, got the block of code and file where this is happening, now gotta reverse engineer!

**Comment by exaskye** [comment]
Hey, I stumbled upon this while browsing GitHub at random. I know a fair amount about codecs, and why this is happening, so, hopefully, my 2¢ here can be helpful.

H.264's main profile only supports YUV 4:2:0, which cuts the color resolution in a quarter (The human eye is much more sensitive to lightness changes than color changes). So, for a 640x480 video, the color information is only 320x240 (divides both sizes in half, therefore making the area a quarter). As such, only even video resolutions work with `-pix_fmt yuv420p`.

YUV 4:4:4 (`-pix_fmt yuv444p`) doesn't have this problem, but it produces much larger files and isn't supported by many players, as 4:4:4 isn't part of the baseline profile (4:4:4 turns off *chroma subsampling*, i.e. color resolution reduction).

Your best option is likely to round down to the closest even number, so that you don't have to invent a new column, row, or both. Nobody will notice a single pixel crop.

(If you've already solved this, sorry for the noise. This issue is still open, so I figured I'd try to help.)

**Comment by julianghionoiu** [comment]
Hey Una,

Thank you so much fo the comprehensive explanation. It makes perfect sense. I was not aware of the division in half done by H.264.

> Your best option is likely to round down to the closest even number, so that you don't have to invent a new column, row, or both. Nobody will notice a single pixel crop.

Indeed this is how we are addressing it.
